### ISSUE TITLE
Code has no license

### ISSUE THREAD

**Issue by stdout-se** [dannyvai/reddit_crawlers#1]
Without a license, there's not really a point in showing off your code. Please license the software so we can work on it. :)

Here's a great intro to licenses if you're not familiar with open source licensing:
https://www.youtube.com/watch?v=9kGrKBOytYM

**Comment by wting** [comment]
[tl;drLegal](https://tldrlegal.com/) has a short explanation of common licenses. I've copy/pasted a few common FOSS ones below:
- [MIT](https://tldrlegal.com/license/mit-license)
- [BSD](https://tldrlegal.com/license/bsd-2-clause-license-%28freebsd%29)
- [GPLv2](https://tldrlegal.com/license/gnu-general-public-license-v2)
- [GPLv3](https://tldrlegal.com/license/gnu-general-public-license-v3-%28gpl-3%29)
- [Apache 2.0](https://tldrlegal.com/license/apache-license-2.0-%28apache-2.0%29)

**Comment by robinlahtinen** [comment]
i recommend creative common cc
